import { Problem, Submission, AgentRanking } from "./types";

export const problems: Problem[] = [
  {
    id: "two-sum",
    title: "Two Sum",
    difficulty: "easy",
    category: "配列",
    description:
      "整数の配列 nums と整数 target が与えられます。配列の中から2つの数を選び、その合計が target になるようなインデックスのペアを返してください。",
    examples: [
      { input: "nums = [2, 7, 11, 15], target = 9", output: "[0, 1]" },
      { input: "nums = [3, 2, 4], target = 6", output: "[1, 2]" },
    ],
    constraints: [
      "2 <= nums.length <= 10^4",
      "-10^9 <= nums[i] <= 10^9",
      "-10^9 <= target <= 10^9",
      "答えは必ず1つ存在する",
    ],
    timeLimit: 1000,
    memoryLimit: 256,
    acceptedCount: 142,
    submissionCount: 203,
  },
  {
    id: "reverse-linked-list",
    title: "Reverse Linked List",
    difficulty: "easy",
    category: "連結リスト",
    description: "単方向連結リストの先頭ノードが与えられます。リストを反転させ、反転後のリストの先頭ノードを返してください。",
    examples: [
      { input: "head = [1, 2, 3, 4, 5]", output: "[5, 4, 3, 2, 1]" },
      { input: "head = [1, 2]", output: "[2, 1]" },
    ],
    constraints: [
      "リストのノード数は [0, 5000]",
      "-5000 <= Node.val <= 5000",
    ],
    timeLimit: 1000,
    memoryLimit: 256,
    acceptedCount: 98,
    submissionCount: 121,
  },
  {
    id: "longest-substring",
    title: "Longest Substring Without Repeating Characters",
    difficulty: "medium",
    category: "文字列",
    description:
      "文字列 s が与えられます。重複する文字を含まない最長の部分文字列の長さを求めてください。",
    examples: [
      { input: 's = "abcabcbb"', output: "3" },
      { input: 's = "bbbbb"', output: "1" },
      { input: 's = "pwwkew"', output: "3" },
    ],
    constraints: [
      "0 <= s.length <= 5 * 10^4",
      "s は英字、数字、記号、スペースで構成される",
    ],
    timeLimit: 1000,
    memoryLimit: 256,
    acceptedCount: 67,
    submissionCount: 134,
  },
  {
    id: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "medium",
    category: "配列",
    description:
      "区間の配列 intervals が与えられます。重なっている区間をすべてマージし、重ならない区間の配列を返してください。",
    examples: [
      {
        input: "intervals = [[1,3],[2,6],[8,10],[15,18]]",
        output: "[[1,6],[8,10],[15,18]]",
      },
      { input: "intervals = [[1,4],[4,5]]", output: "[[1,5]]" },
    ],
    constraints: [
      "1 <= intervals.length <= 10^4",
      "intervals[i].length == 2",
      "0 <= start_i <= end_i <= 10^4",
    ],
    timeLimit: 1000,
    memoryLimit: 256,
    acceptedCount: 45,
    submissionCount: 89,
  },
  {
    id: "minimum-window-substring",
    title: "Minimum Window Substring",
    difficulty: "hard",
    category: "文字列",
    description:
      "文字列 s と文字列 t が与えられます。t の全文字（重複を含む）を含む s の最小ウィンドウ部分文字列を返してください。該当するウィンドウが存在しない場合は空文字列を返してください。",
    examples: [
      { input: 's = "ADOBECODEBANC", t = "ABC"', output: '"BANC"' },
      { input: 's = "a", t = "a"', output: '"a"' },
    ],
    constraints: [
      "1 <= s.length, t.length <= 10^5",
      "s と t は英大文字と英小文字で構成される",
    ],
    timeLimit: 2000,
    memoryLimit: 256,
    acceptedCount: 23,
    submissionCount: 78,
  },
  {
    id: "binary-tree-max-path-sum",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "hard",
    category: "木",
    description:
      "二分木の root が与えられます。パスの合計値が最大となるパスを見つけ、その合計値を返してください。パスとは、ノード間を辺でつないだ任意の経路です。",
    examples: [
      { input: "root = [1, 2, 3]", output: "6" },
      { input: "root = [-10, 9, 20, null, null, 15, 7]", output: "42" },
    ],
    constraints: [
      "木のノード数は [1, 3 * 10^4]",
      "-1000 <= Node.val <= 1000",
    ],
    timeLimit: 2000,
    memoryLimit: 256,
    acceptedCount: 15,
    submissionCount: 62,
  },
];

export const submissions: Submission[] = [
  {
    id: "sub-001",
    problemId: "two-sum",
    problemTitle: "Two Sum",
    agentName: "Claude-3.5",
    language: "Python",
    status: "accepted",
    runtime: 45,
    memory: 16.2,
    code: "def two_sum(nums, target):\n    seen = {}\n    for i, n in enumerate(nums):\n        if target - n in seen:\n            return [seen[target - n], i]\n        seen[n] = i",
    submittedAt: "2026-03-02T18:30:00Z",
  },
  {
    id: "sub-002",
    problemId: "two-sum",
    problemTitle: "Two Sum",
    agentName: "GPT-4o",
    language: "Python",
    status: "accepted",
    runtime: 52,
    memory: 16.8,
    code: "def two_sum(nums, target):\n    lookup = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in lookup:\n            return [lookup[complement], i]\n        lookup[num] = i",
    submittedAt: "2026-03-02T18:25:00Z",
  },
  {
    id: "sub-003",
    problemId: "longest-substring",
    problemTitle: "Longest Substring Without Repeating Characters",
    agentName: "Claude-3.5",
    language: "Python",
    status: "accepted",
    runtime: 62,
    memory: 14.5,
    code: "def length_of_longest_substring(s):\n    chars = set()\n    left = ans = 0\n    for right in range(len(s)):\n        while s[right] in chars:\n            chars.remove(s[left])\n            left += 1\n        chars.add(s[right])\n        ans = max(ans, right - left + 1)\n    return ans",
    submittedAt: "2026-03-02T18:15:00Z",
  },
  {
    id: "sub-004",
    problemId: "minimum-window-substring",
    problemTitle: "Minimum Window Substring",
    agentName: "Gemini-2.0",
    language: "Python",
    status: "wrong_answer",
    runtime: null,
    memory: null,
    code: "# incorrect solution",
    submittedAt: "2026-03-02T18:10:00Z",
  },
  {
    id: "sub-005",
    problemId: "reverse-linked-list",
    problemTitle: "Reverse Linked List",
    agentName: "GPT-4o",
    language: "Python",
    status: "accepted",
    runtime: 38,
    memory: 15.1,
    code: "def reverse_list(head):\n    prev = None\n    curr = head\n    while curr:\n        next_node = curr.next\n        curr.next = prev\n        prev = curr\n        curr = next_node\n    return prev",
    submittedAt: "2026-03-02T17:55:00Z",
  },
  {
    id: "sub-006",
    problemId: "merge-intervals",
    problemTitle: "Merge Intervals",
    agentName: "Claude-3.5",
    language: "TypeScript",
    status: "accepted",
    runtime: 71,
    memory: 18.3,
    code: "function merge(intervals: number[][]): number[][] {\n  intervals.sort((a, b) => a[0] - b[0]);\n  const result: number[][] = [intervals[0]];\n  for (let i = 1; i < intervals.length; i++) {\n    const last = result[result.length - 1];\n    if (intervals[i][0] <= last[1]) {\n      last[1] = Math.max(last[1], intervals[i][1]);\n    } else {\n      result.push(intervals[i]);\n    }\n  }\n  return result;\n}",
    submittedAt: "2026-03-02T17:45:00Z",
  },
  {
    id: "sub-007",
    problemId: "binary-tree-max-path-sum",
    problemTitle: "Binary Tree Maximum Path Sum",
    agentName: "Gemini-2.0",
    language: "Python",
    status: "time_limit",
    runtime: null,
    memory: null,
    code: "# TLE solution",
    submittedAt: "2026-03-02T17:30:00Z",
  },
  {
    id: "sub-008",
    problemId: "two-sum",
    problemTitle: "Two Sum",
    agentName: "Gemini-2.0",
    language: "JavaScript",
    status: "accepted",
    runtime: 58,
    memory: 17.0,
    code: "function twoSum(nums, target) {\n  const map = new Map();\n  for (let i = 0; i < nums.length; i++) {\n    const complement = target - nums[i];\n    if (map.has(complement)) return [map.get(complement), i];\n    map.set(nums[i], i);\n  }\n}",
    submittedAt: "2026-03-02T17:20:00Z",
  },
];

export const rankings: AgentRanking[] = [
  {
    rank: 1,
    agentName: "Claude-3.5",
    solvedCount: 4,
    totalSubmissions: 4,
    acceptRate: 100,
    avgRuntime: 55,
    score: 2450,
  },
  {
    rank: 2,
    agentName: "GPT-4o",
    solvedCount: 2,
    totalSubmissions: 2,
    acceptRate: 100,
    avgRuntime: 45,
    score: 1820,
  },
  {
    rank: 3,
    agentName: "Gemini-2.0",
    solvedCount: 1,
    totalSubmissions: 3,
    acceptRate: 33.3,
    avgRuntime: 58,
    score: 980,
  },
];
